Provide AlertManager-specific configuration as resources
relaxdiego/charm-k8s-alertmanager pull request #2
Opened 2020-06-03 09:52 UTC by relaxdiego

This change uses Juju's resource CLI option to set AlertManager's config
file. The rationale for this is so that systems administrators who want
to re-use an existing alertmanager.yml file can do so. This also avoids
the "abstraction over an abstraction" problem that would be present if
AlertManager-specific configuration was defined via the charm's
config.yml file. For example, AlertManager's inhibit_rules config would
have to be hand-massaged by the charm user to fit whatever is defined in
the charm's config.yaml file.

2020-06-03 09:57 UTC, relaxdiego commented
@exceptorr This is still draft and I have yet to update and add more unit tests. However, I wanted to get your early feedback from you to know what you think of this approach.

2020-06-03 10:02 UTC, relaxdiego commented
I think it makes sense to use `config.yaml` for configuring the charm but use `--resource` to pass the configuration for the app being managed by the charm.

2020-06-04 04:33 UTC, relaxdiego commented
Another possible design choice is that the `alertmanager-config` and `alertmanager-secrets` resources are available for advanced charm users but for beginner or intermediate users, a limited set of configuration options is available via the charm's `config.yml`. Let's call these two scenarios **ADVANCED configuration** and **SIMPLIFIED configuration** respectively.

When using the **ADVANCED** configuration, the charm will exclusively use the files given via `alertmanager-config` and, when present, `alertmanager-secrets`.

When using the **SIMPLIFIED** configuration, the charm will first load a static alertmanager config file with sane defaults and then overwrite some of the appropriate settings with what is given by the charm user via the `--config` option.

2020-06-04 07:14 UTC, relaxdiego commented
Example `juju deploy` command

```
juju deploy . \
  --resource alertmanager-config=$HOME/.alertmanager/config.yml \
  --resource alertmanager-secrets=$HOME/.alertmanager/secrets.yml \
  --resource prometheus-image=prom/prometheus:v2.18.1 \
  --config global_smtp_from='foo@bar.com'
```

2020-06-04 08:16 UTC, relaxdiego commented
Cross referencing [a Discourse thread that I started earlier](https://discourse.juju.is/t/how-to-reconcile-config-yamls-deliberate-restrictiveness-with-hierarchical-app-config/3184?u=mmaglana).

2020-06-04 11:54 UTC, exceptorr commented
Why can't we simplify this and implement the Alertmanager configuration using direct YAML injection, rather than playing around with the resources?

The problem here is that you won't be able to supply a simple "just deploy it" bundle, you'll have to provide the resource files as well; while by giving an option to supply YAML manually you're giving some freedom to the charm operator AND allowing him to use basic IaC concepts by exporting his configs via `juju export-bundle`, for example.

2020-06-04 12:02 UTC, relaxdiego commented
> Why can't we simplify this and implement the Alertmanager configuration using direct YAML injection, rather than playing around with the resources?

I’m interested. What would the CLI command look like in this case?

2020-06-04 12:04 UTC, exceptorr commented
`juju config alertmanager config-file=$(base64 alertmanager-config.yaml)` for example (the same approach was taken for the ssl-* config options in the OpenStack charms)

2020-06-04 12:04 UTC, exceptorr commented
Or, `include-base64:///home/ubuntu/alertmanager-config.yaml` in the bundle, if `juju deploy ...` is invoked.

2020-06-04 12:06 UTC, exceptorr commented
Well, technically, we don't even have to use base64 - I don't know an exact reason why b64 encoding was chosen (probably, to avoid formatting and whitespace problems) - but the approach will remain the same anyway.

2020-06-04 13:43 UTC, relaxdiego commented
@exceptorr: Alright, for my next pass I'm going to exclusively use the `--config` method you described even though [this documentation discourages it](https://discourse.juju.is/t/how-to-reconcile-config-yamls-deliberate-restrictiveness-with-hierarchical-app-config/3184) because your argument makes a lot of sense from a user experience perspective. 

I will also make use of [Juju 2.7's support for k8s secrets](https://discourse.juju.is/t/updated-podspec-yaml-new-features/2124) to turn the config file into a k8s secret before mounting onto the container.

2020-06-05 07:44 UTC, relaxdiego commented on src/adapters/framework.py
> +
Dead code. Needs to be removed.

2020-06-10 16:21 UTC, exceptorr requested changes
Looks good, one small comment and we're good to go!

2020-06-10 16:21 UTC, exceptorr commented on src/domain.py
> +    # TODO: Remove this before merging as it exposes sensitive config info
Remove this? :-)

2020-06-10 20:44 UTC, relaxdiego commented on src/domain.py
> +    # TODO: Remove this before merging as it exposes sensitive config info
LOL yes.

2020-06-10 23:55 UTC, relaxdiego commented
@exceptorr being that you've given your conditional approval and that i've addressed it, I'm going to go ahead and merge this baby.

2020-06-10 23:56 UTC, merged